---@meta
---@module "solver/problem_generator"

---@alias FilterType "item"|"fluid"|"recipe"|"machine"|"virtual_material"|"virtual_recipe"|"transfer"
-- Constraint-picker tab selector. "external" is a UI-only view over virtual_recipe
-- (the source/sink recipes), not a real material/recipe FilterType — the typed
-- names it yields are still "virtual_recipe".
---@alias FilterTab FilterType|"external"
---@alias LimitType "upper"|"lower"|"equal"
---@alias TimeScale "second"|"five_seconds"|"minute"|"ten_minutes"|"hour"|"ten_hours"|"fifty_hours"|"two_hundred_fifty_hours"|"thousand_hours"
---@alias AmountUnit "time"|"belt"|"storage"
---@alias EnergyType "electric"|"burner"|"heat"|"fluid"|"void"
---@alias SolverState integer|"ready"|"finished"|"unfinished"|"unbounded"|"unfeasible"
---@alias Craft LuaItemPrototype|LuaFluidPrototype|LuaRecipePrototype|LuaEntityPrototype|VirtualMaterial|VirtualRecipe
-- Fluid temperature is carried range-only: a point temperature is the degenerate
-- range minimum_temperature == maximum_temperature. There is no single-value
-- `temperature` field; that asymmetry lived only in the raw recipe layer
-- (Product.temperature) and is collapsed to [T,T] at the normalization boundary.
---@alias TypedName { type: FilterType, name: string, quality: string, minimum_temperature: number?, maximum_temperature: number? }
---@alias ProductEx Product|VirtualProduct
---@alias IngredientEx Ingredient|VirtualIngredient

---@class EventDataTrait
---@field element LuaGuiElement
---@field mod_name string?
---@field name string | defines.events
---@field player_index integer
---@field tick integer

---@class Storage
---@field players table<integer, PlayerLocalData>
---@field forces table<integer, ForceLocalData>
---@field virtuals Virtuals
__factory_solver__storage = {}

---@class PlayerLocalData
---@field selected_solution string
---@field selected_filter_type FilterTab
---@field selected_filter_group table<FilterTab, string>
---@field unresearched_craft_visible boolean
---@field hidden_craft_visible boolean
---@field time_scale TimeScale
---@field amount_unit AmountUnit
---@field presets Presets
---@field opened_gui string[]
---@field machine_clipboard MachineClipboard?
---@field module_clipboard TypedName?

---Per-player clipboard for the Shift+Click copy/paste flow over production
---line rows in solution_editor. A copy snapshots the whole machine-side
---configuration of the source line; the `mode` flag selects which subset
---paste applies to the target line. Storing both halves regardless of mode
---keeps the data structure mode-independent and lets the user copy once and
---decide later — at click time — which subset to paste where.
---@class MachineClipboard
---@field mode "machine_fuel"|"module_beacon"
---@field machine_typed_name TypedName
---@field fuel_typed_name TypedName?
---@field substrate_tile_name string?
---@field module_typed_names table<string, TypedName>
---@field affected_by_beacons AffectedByBeacon[]

---@class Presets
---@field fuel table<string, TypedName>
---@field fluid_fuel TypedName
---@field resource table<string, TypedName>
---@field machine table<string, TypedName>
---@field pump table<string, TypedName>
---@field lab table<string, TypedName>

---@class ForceLocalData
---@field relation_to_recipes RelationToRecipes
---@field relation_to_recipes_needs_updating boolean
---@field group_infos GroupInfos
---@field group_infos_needs_updating boolean
---@field solutions table<string, Solution>
---@field research_bonuses ResearchBonuses

---Per-force snapshot of research-derived bonuses. Always opt-in: defaults to
---all zero / "normal" only, populated only when the user clicks Apply in the
---Research bonuses dialog. The solver reads this snapshot; LuaForce runtime
---values are never read inside the solve path.
---@class ResearchBonuses
---@field recipe_productivity table<string, number>
---@field mining_drill_productivity number
---@field laboratory_productivity number
---@field laboratory_speed number
---@field beacon_distribution number
---@field research_unit_energy number
---@field unlocked_qualities table<string, boolean>

---@class RelationToRecipes
---@field enabled_recipe table<string, boolean>
---@field item table<string, RelationToRecipe>
---@field fluid table<string, RelationToRecipe>
---@field virtual_recipe table<string, RelationToRecipe>
---@field virtual_recipe_researched table<string, boolean>

---@class RelationToRecipe
---@field craftable_count integer
---@field recipe_for_product string[]
---@field recipe_for_ingredient string[]
---@field recipe_for_fuel string[]

---@class GroupInfos
---@field item table<string, GroupInfo>
---@field fluid table<string, GroupInfo>
---@field recipe table<string, GroupInfo>
---@field virtual_recipe table<string, GroupInfo>
---@field external table<string, GroupInfo>

---@class GroupInfo
---@field hidden_count integer
---@field unresearched_count integer
---@field researched_count integer

---@class Solution
---@field name string
---@field constraints Constraint[]
---@field production_lines ProductionLine[]
---@field quantity_of_machines_required table<string, number>
---@field inactive_recipe_variables table<string, true>?
---@field problem Problem?
---@field solver_state SolverState
---@field raw_variables PackedVariables?
---@field done_lines table<string, true>?

---@class Constraint
---@field type FilterType
---@field name string
---@field quality string
---@field minimum_temperature number?
---@field maximum_temperature number?
---@field limit_type LimitType
---@field limit_amount_per_second number

---@class ProductionLine
---@field recipe_typed_name TypedName
---@field machine_typed_name TypedName
---@field module_typed_names table<string, TypedName>
---@field affected_by_beacons AffectedByBeacon[]
---@field fuel_typed_name TypedName?
---@field substrate_tile_name string?

---@class AffectedByBeacon
---@field beacon_typed_name TypedName?
---@field beacon_quantity integer
---@field module_typed_names table<string, TypedName>

---Per-source module aggregation produced by accessor.get_total_modules.
---machine_modules contains modules sitting in the machine's own slots.
---beacon_groups holds one entry per beacon attached to the line, with
---per-module counts already scaled by that beacon's distribution effectivity.
---Splitting by source lets get_total_effectivity apply
---(recipe ∩ machine).allowed_effects to machine modules and
---(recipe ∩ beacon).allowed_effects to each beacon's modules independently.
---@class TotalModules
---@field machine_modules table<string, table<string, number>>
---@field beacon_groups { beacon: LuaEntityPrototype, modules: table<string, table<string, number>> }[]

---@class PackedVariables
---@field x table<string, number>
---@field y table<string, number>
---@field s table<string, number>

---@class NormalizedProductionLine
---@field recipe_typed_name TypedName
---@field products NormalizedAmount[]
---@field ingredients NormalizedAmount[]
---@field fuel_ingredient NormalizedAmount?
---@field power_per_second number
---@field pollution_per_second number

---@class NormalizedAmount
---@field type "item"|"fluid"|"virtual_material"
---@field name string
---@field quality string
---@field amount_per_second number
---@field minimum_temperature number?
---@field maximum_temperature number?

---@class Virtuals
---@field material table<string, VirtualMaterial>
---@field recipe table<string, VirtualRecipe>
---@field fuel_categories_dictionary table<string, { [string]: true }>

---@class VirtualMaterial
---@field type "virtual_material"
---@field name string
---@field sprite_path string
---@field tooltip LocalisedString?
---@field elem_tooltip ElemID?
---@field order string
---@field group_name string
---@field subgroup_name string
---@field hidden boolean
---@field source_entity_name string?
---@field source_fluid_name string?

---Virtual recipes describe machine-driven conversions that have no LuaRecipePrototype
---(boiler heating, generator fuel burn, mining, plant growth, lab research,
---rocket launches, ...). Unlike real recipes, the per-second rate is not
---encoded in `products[i].amount` / `ingredients[i].amount`; those fields
---hold per-craft ratios (typically 1 for shape-only recipes, or a recipe-
---specific stoichiometry like 1/heat_capacity for boilers). The per-second
---throughput baseline is supplied at pre_solve time by
---accessor.get_virtual_recipe_rates(machine, quality), which dispatches per
---machine type to whichever quality-aware runtime API actually scales for
---that entity. accessor.normalize_production_line then multiplies the ratio
---by the rate to get per-second values for the LP.
---@class VirtualRecipe
---@field type "virtual_recipe"
---@field name string
---@field sprite_path string
---@field tooltip LocalisedString?
---@field elem_tooltip ElemID?
---@field order string
---@field group_name string
---@field subgroup_name string
---@field products ProductEx[]
---@field ingredients IngredientEx[]
---@field fixed_crafting_machine TypedName?
---@field resource_category string?
---@field pumped_fluid_name string?
---@field consumed_pack_name string?
---@field crafting_speed_cap number?
---@field pollution_per_craft number?
---@field hidden boolean
---@field source_entity_name string?
---@field source_planet_names string[]?
---@field is_spoilage boolean?
---@field is_source boolean?
---@field is_sink boolean?

---@class VirtualProduct
---@field type "virtual_material"
---@field name string
---@field amount number?
---@field amount_min number?
---@field amount_max number?
---@field probability number
---@field ignored_by_productivity number?
---@field temperature number?

---@class VirtualIngredient
---@field type "virtual_material"
---@field name string
---@field amount number
---@field minimum_temperature number?
---@field maximum_temperature number?

---Project-local mirror of `flib.GuiElemDef`. flib defines its type as a
---single `@class` inheriting from a union of `LuaGuiElement.add_param.*`
---variants, but since factoriomod-debug 2.0.11 those variants are
---`(exact)` and LuaLS no longer narrows `type` correctly through that
---inheritance — every site assigning `type = "frame"` etc. is flagged
---as `assign-type-mismatch` against `"button"` (the first variant). The
---workaround is to express the same shape as an `@alias` union of
---per-variant classes, which LuaLS narrows on the literal `type`. Each
---variant combines the upstream `(exact)` add_param class with the flib
---extras (`handler`, `children`, etc.) via multiple inheritance.
---
---`fs_util.add_gui` casts to `flib.GuiElemDef` at the actual flib
---boundary so flib's signature is satisfied at runtime.
---@class fs.GuiElemDef.extras
---@field style_mods LuaStyle?
---@field elem_mods LuaGuiElement?
---@field drag_target string?
---@field handler any?
---@field children fs.GuiElemDef[]?
---@field tab fs.GuiElemDef?
---@field content fs.GuiElemDef?

---@class fs.GuiElemDef.button: LuaGuiElement.add_param.button, fs.GuiElemDef.extras
---@class fs.GuiElemDef.camera: LuaGuiElement.add_param.camera, fs.GuiElemDef.extras
---@class fs.GuiElemDef.checkbox: LuaGuiElement.add_param.checkbox, fs.GuiElemDef.extras
---@class fs.GuiElemDef.choose_elem_button: LuaGuiElement.add_param.choose_elem_button, fs.GuiElemDef.extras
---@class fs.GuiElemDef.drop_down: LuaGuiElement.add_param.drop_down, fs.GuiElemDef.extras
---@class fs.GuiElemDef.flow: LuaGuiElement.add_param.flow, fs.GuiElemDef.extras
---@class fs.GuiElemDef.frame: LuaGuiElement.add_param.frame, fs.GuiElemDef.extras
---@class fs.GuiElemDef.line: LuaGuiElement.add_param.line, fs.GuiElemDef.extras
---@class fs.GuiElemDef.list_box: LuaGuiElement.add_param.list_box, fs.GuiElemDef.extras
---@class fs.GuiElemDef.minimap: LuaGuiElement.add_param.minimap, fs.GuiElemDef.extras
---@class fs.GuiElemDef.progressbar: LuaGuiElement.add_param.progressbar, fs.GuiElemDef.extras
---@class fs.GuiElemDef.radiobutton: LuaGuiElement.add_param.radiobutton, fs.GuiElemDef.extras
---@class fs.GuiElemDef.scroll_pane: LuaGuiElement.add_param.scroll_pane, fs.GuiElemDef.extras
---@class fs.GuiElemDef.slider: LuaGuiElement.add_param.slider, fs.GuiElemDef.extras
---@class fs.GuiElemDef.sprite: LuaGuiElement.add_param.sprite, fs.GuiElemDef.extras
---@class fs.GuiElemDef.sprite_button: LuaGuiElement.add_param.sprite_button, fs.GuiElemDef.extras
---@class fs.GuiElemDef.switch: LuaGuiElement.add_param.switch, fs.GuiElemDef.extras
---@class fs.GuiElemDef.tab: LuaGuiElement.add_param.tab, fs.GuiElemDef.extras
---@class fs.GuiElemDef.table: LuaGuiElement.add_param.table, fs.GuiElemDef.extras
---@class fs.GuiElemDef.text_box: LuaGuiElement.add_param.text_box, fs.GuiElemDef.extras
---@class fs.GuiElemDef.textfield: LuaGuiElement.add_param.textfield, fs.GuiElemDef.extras
---@class fs.GuiElemDef.base: LuaGuiElement.add_param.base, fs.GuiElemDef.extras

---@alias fs.GuiElemDef
---| fs.GuiElemDef.button
---| fs.GuiElemDef.camera
---| fs.GuiElemDef.checkbox
---| fs.GuiElemDef.choose_elem_button
---| fs.GuiElemDef.drop_down
---| fs.GuiElemDef.flow
---| fs.GuiElemDef.frame
---| fs.GuiElemDef.line
---| fs.GuiElemDef.list_box
---| fs.GuiElemDef.minimap
---| fs.GuiElemDef.progressbar
---| fs.GuiElemDef.radiobutton
---| fs.GuiElemDef.scroll_pane
---| fs.GuiElemDef.slider
---| fs.GuiElemDef.sprite
---| fs.GuiElemDef.sprite_button
---| fs.GuiElemDef.switch
---| fs.GuiElemDef.tab
---| fs.GuiElemDef.table
---| fs.GuiElemDef.text_box
---| fs.GuiElemDef.textfield
---| fs.GuiElemDef.base
