---@diagnostic disable: undefined-global
-- Generate tests/fixtures/bundle16_v060.lua: the frozen "good" baseline that
-- check_bundle16_v060 (manage/smoke_rcon.lua) guards the current shipping solver
-- against. The baseline is the 0.6.0 solver's solution for each bundle Solution.
--
-- Self-bootstrapping (does NOT require tests/headless_env, which 0.6.0 lacks), so
-- it runs unchanged inside an OLD-version worktree:
--   1. capture clean normalized lines with the CURRENT (data_test-fixed) build:
--      & tests/smoke_rcon.ps1 -Mods base,flib,factory_solver,space-age,quality,elevated-rails -KeepRun
--      -> write/script-output/bundle16_normalized.lua   (must be a build where
--         data_test.lua's fs-test recipes carry auto_recycle=false, else recycling
--         products are corrupted and baked into the capture).
--   2. git worktree add <dir> 0.6.0
--   3. cd <dir> && lua <this file copied in> <path>/bundle16_normalized.lua <path>/bundle16_v060.lua
--      (run from the worktree root so `require "solver/..."` resolves to 0.6.0's solver).
--
-- Metrics are aggregate tier sums, robust to degenerate-face vertex wobble:
--   T target-violation (elastic), import = |shortage_source| + |initial_source|
--   (the kind split differs across the gate change but the SUM is invariant),
--   surplus = |surplus_sink|, machines = sum over the PLACED-line recipe vars
--   (== current solver's kind=="recipe"). 0.6.0 has no Primal.kind, so machines
--   is summed by the exact placed-line variable keys instead.

package.path = "./?.lua;./?/init.lua;" .. package.path
package.preload["__flib__/format"] = function()
    local f = {}; function f.number(a) return tostring(a) end; return f
end

local create_problem = require "solver/create_problem"
local lp = require "solver/linear_programming"
local harness = require "tests/harness"
local tn = require "manage/typed_name"

local in_path = arg[1] or error("usage: lua tests/bundle16_make_v060.lua <bundle16_normalized.lua> [out]")
local out_path = arg[2] or "tests/fixtures/bundle16_v060.lua"
local bundle = assert(loadfile(in_path))()

local names = {}
for n in pairs(bundle) do names[#names + 1] = n end
table.sort(names)

local TOL, ITER = 1e-7, 800
local function nf(x)
    if x == math.floor(x) then return string.format("%d", x) end
    return string.format("%.10g", x)
end

local out = {
    "-- The 0.6.0 solver's solution for every Solution in bundle16_shared.lua, the",
    "-- GOOD baseline that check_bundle16_v060 guards the current solver against.",
    "-- machines = sum over the PLACED-line recipe vars (== current kind=='recipe').",
    "-- Generated by tests/bundle16_make_v060.lua in a 0.6.0 git worktree. NOT shipped.",
    "return {",
}
for _, name in ipairs(names) do
    local b = bundle[name]
    local placed = {}
    for _, ln in ipairs(b.lines) do placed[tn.typed_name_to_variable_name(ln.recipe_typed_name)] = true end
    local ok, problem = pcall(create_problem.create_problem, name, b.constraints, b.lines)
    local state, vars = "create_problem-error", nil
    if ok then state, vars = harness.solve_to_completion(lp, problem, { tolerance = TOL, iterate_limit = ITER }) end
    local M, imp, sur, T = 0, 0, 0, 0
    if state == "finished" then
        for k, v in pairs(vars.x) do
            v = math.abs(v)
            if placed[k] then M = M + v
            elseif k:sub(1, 17) == "|shortage_source|" or k:sub(1, 16) == "|initial_source|" then imp = imp + v
            elseif k:sub(1, 14) == "|surplus_sink|" then sur = sur + v
            elseif k:sub(1, 9) == "|elastic|" then T = T + v end
        end
    end
    out[#out + 1] = string.format(
        "    [%q] = { state = %q, T = %s, import = %s, surplus = %s, machines = %s },",
        name, state, nf(T), nf(imp), nf(sur), nf(M))
    io.write(string.format("  %-22s state=%-10s M=%s\n", name, state, nf(M)))
end
out[#out + 1] = "}"
out[#out + 1] = ""

local f = assert(io.open(out_path, "w"))
f:write(table.concat(out, "\n"))
f:close()
io.write("wrote " .. out_path .. "\n")
