-- Marker scenario for the in-game smoke test. The actual driver lives in
-- [manage/smoke.lua](../../manage/smoke.lua), which the mod activates when
-- script.level.level_name == "smoke" (see the gate at the bottom of
-- [control.lua](../../control.lua)).
--
-- Scenarios run in their own Lua context with a separate `storage`, so we
-- cannot poke at mod state from here. Keeping this file empty avoids the
-- temptation. Launch via:
--   factorio.exe --load-scenario factory_solver/smoke
